name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Application
      run: pyinstaller --onefile main.py

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: your-application
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: your-application
          path: dist/

      - name: Generate Tag
        id: generate_tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"
        # Cela génère un tag basé sur la date et l'heure actuelle

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          release_name: Release ${{ steps.generate_tag.outputs.tag }}
          body: "Description of the release"
          draft: false
          prerelease: false

