name: Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Etape pour vérifier le message de commit
      - name: Check Commit Message for 'nouvelle version'
        id: commit_filter
        run: |
          echo "Checking for 'nouvelle version' in the commit message..."
          if git log -1 --pretty=%B | grep -iq "nouvelle version"; then
            echo "SHOULD_RUN=true" >> $GITHUB_ENV
            echo "Le message du commit posssede : nouvelle version."
          else
            echo "SHOULD_RUN=false" >> $GITHUB_ENV
            echo "Le workflow ne va pas creer de release."
          fi
      - name: Set up Python
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      # Installation des dépendances Python
      - name: Install dependencies
        if: env.SHOULD_RUN == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Construction de l'exécutable avec PyInstaller
      - name: Build Application
        if: env.SHOULD_RUN == 'true'
        run: pyinstaller --onefile main.py

      # Archivage de l'exécutable
      - name: Archive Production Artifacts
        if: env.SHOULD_RUN == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: Logiciel Feuilles de caisses 
          path: dist/

 # Step pour récupérer la dernière balise annotée et extraire la version
      - name: Get latest tag and set new tag name
        id: versioning
        run: |
          if ! latest_tag=$(git describe --tags --abbrev=0 2>/dev/null); then
            echo "No tags found. Setting a default tag."
            latest_tag="v0.0.0" # Définissez ici le tag par défaut que vous souhaitez utiliser
          fi
          echo "Latest tag: $latest_tag"
          # Supposons que le format du tag est vMajor.Minor.Patch
          major=$(echo $latest_tag | cut -d '.' -f 1 | sed 's/v//')
          minor=$(echo $latest_tag | cut -d '.' -f 2)
          patch=$(echo $latest_tag | cut -d '.' -f 3)
          new_patch=$((patch + 1)) # Incrémentation du numéro de patch
          NEW_TAG="v${major}.${minor}.${new_patch}"
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        shell: bash


      # Utilisation du nouveau tag pour les étapes suivantes
      - name: Use new tag
        run: |
          echo "Using new tag ${{ env.NEW_TAG }} for operations"

      # Création de la release GitHub avec l'exécutable
      - name: Create Release
        if: env.SHOULD_RUN == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }} 
          release_name: Release ${{ env.NEW_TAG }}
          body: "Description of the release"
          draft: false
          prerelease: false

