name: Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Etape pour vérifier le message de commit
      - name: Check Commit Message for 'nouvelle version'
        id: commit_filter
        run: |
          echo "Checking for 'nouvelle version' in the commit message..."
          if git log -1 --pretty=%B | grep -iq "nouvelle version"; then
            echo "SHOULD_RUN=true" >> $GITHUB_ENV
            echo "Le message du commit posssede : nouvelle version."
          else
            echo "SHOULD_RUN=false" >> $GITHUB_ENV
            echo "Le workflow ne va pas creer de release."
            exit 1 # Arrête le job si 'nouvelle version' n'est pas trouvé
          fi
            # Configuration de l'environnement Python
      - name: Set up Python
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      # Installation des dépendances Python
      - name: Install dependencies
        if: env.SHOULD_RUN == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Construction de l'exécutable avec PyInstaller
      - name: Build Application
        if: env.SHOULD_RUN == 'true'
        run: pyinstaller --onefile main.py

      # Archivage de l'exécutable
      - name: Archive Production Artifacts
        if: env.SHOULD_RUN == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: Logiciel Feuilles de caisses 
          path: dist/

      # Génération d'un tag basé sur la date et l'heure
      - name: Generate Tag
        if: env.SHOULD_RUN == 'true'
        run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Création de la release GitHub avec l'exécutable
      - name: Create Release
        if: env.SHOULD_RUN == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: "Description of the release"
          draft: false
          prerelease: false
